// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerhuurApplicatieAPI.Data;

#nullable disable

namespace VerhuurApplicatieAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522103809_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VerhuurApplicatieAPI.Models.Auto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AantalZitplaatsen")
                        .HasColumnType("int");

                    b.Property<string>("AfbeeldingUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Beschikbaar")
                        .HasColumnType("bit");

                    b.Property<int>("Bouwjaar")
                        .HasColumnType("int");

                    b.Property<string>("Brandstof")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kenteken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrijsPerDag")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Autos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AantalZitplaatsen = 5,
                            Beschikbaar = true,
                            Bouwjaar = 2020,
                            Brandstof = "Benzine",
                            Kenteken = "AB-123-C",
                            Merk = "Toyota",
                            Model = "Corolla",
                            PrijsPerDag = 45.00m
                        },
                        new
                        {
                            Id = 2,
                            AantalZitplaatsen = 5,
                            Beschikbaar = true,
                            Bouwjaar = 2021,
                            Brandstof = "Benzine",
                            Kenteken = "DE-456-F",
                            Merk = "Volkswagen",
                            Model = "Golf",
                            PrijsPerDag = 55.00m
                        },
                        new
                        {
                            Id = 3,
                            AantalZitplaatsen = 5,
                            Beschikbaar = true,
                            Bouwjaar = 2023,
                            Brandstof = "Elektrisch",
                            Kenteken = "GH-789-I",
                            Merk = "Tesla",
                            Model = "Model 3",
                            PrijsPerDag = 85.00m
                        },
                        new
                        {
                            Id = 4,
                            AantalZitplaatsen = 5,
                            Beschikbaar = false,
                            Bouwjaar = 2019,
                            Brandstof = "Diesel",
                            Kenteken = "JK-012-L",
                            Merk = "Ford",
                            Model = "Focus",
                            PrijsPerDag = 40.00m
                        });
                });

            modelBuilder.Entity("VerhuurApplicatieAPI.Models.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klanten");
                });

            modelBuilder.Entity("VerhuurApplicatieAPI.Models.Reservatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EindDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AutoId");

                    b.HasIndex("KlantId");

                    b.ToTable("Reservaties");
                });

            modelBuilder.Entity("VerhuurApplicatieAPI.Models.Reservatie", b =>
                {
                    b.HasOne("VerhuurApplicatieAPI.Models.Auto", "Auto")
                        .WithMany("Reservaties")
                        .HasForeignKey("AutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VerhuurApplicatieAPI.Models.Klant", "Klant")
                        .WithMany("Reservaties")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auto");

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("VerhuurApplicatieAPI.Models.Auto", b =>
                {
                    b.Navigation("Reservaties");
                });

            modelBuilder.Entity("VerhuurApplicatieAPI.Models.Klant", b =>
                {
                    b.Navigation("Reservaties");
                });
#pragma warning restore 612, 618
        }
    }
}
